#!/bin/sh /etc/rc.common

#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: ISC

START=99
STOP=01
USE_PROCD=1

PRPLMESH_DIR="/opt/prplmesh/"

start_service() {
        procd_open_instance
        procd_set_param command "$PRPLMESH_DIR/scripts/beerocks_agent_launcher.sh"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param term_timeout 1
        procd_close_instance
}

stop_service(){
        killall beerocks_agent
}

